### ISSUE TITLE
Could not load file or assembly 'System.Xml, Version=4.0.0.0... when instantiating OpenIdConnectOptions

### ISSUE THREAD

**Issue by mattbrewer** [aspnet/Security#1003]
We are trying to get a .Net Core web application to run on Azure.  It currently runs on a local development machine without issue, which makes debugging interesting.

When it is bootstrapped in Azure, the follow exception gets thrown:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: 
Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
  at Microsoft.AspNetCore.Builder.OpenIdConnectOptions..ctor(String authenticationScheme)
  at Microsoft.AspNetCore.Builder.OpenIdConnectOptions..ctor()
```

OIDC is being initialized in `Startup` using the following method:
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IOptions<OpenIdConnectOptions> oidcOptions)
        {
           ...
           app.UseOpenIdConnectAuthentication(oidcOptions.Value);
           ...
        }
```

When this line is removed, the site runs fine... without OIDC, of course

Here is the setup of `OpenIdConnectOptions` in `Startup`:
```c#
        public void ConfigureServices(IServiceCollection services)
        {
           ....
            // Configure OIDC
            services.Configure<OpenIdConnectOptions>(options =>
            {
                // Specify Authentication Scheme
                options.AuthenticationScheme = "Auth0";

                // Set the authority to your Auth0 domain
                options.Authority = $"https://{this.Configuration["Auth0:Domain"]}";

                // Configure the Auth0 Client ID and Client Secret
                options.ClientId = this.Configuration["Auth0:ClientId"];
                options.ClientSecret = this.Configuration["Auth0:ClientSecret"];

                // Do not automatically authenticate and challenge
                options.AutomaticAuthenticate = false;
                options.AutomaticChallenge = false;

                // Set response type to code
                options.ResponseType = "code";

                // Set the callback path, so Auth0 will call back to http://localhost:*/signin-auth0 
                // Also ensure that you have added the URL as an Allowed Callback URL in your Auth0 dashboard 
                options.CallbackPath = new PathString(this.Configuration["Auth0:CallbackUrl"]);

                // Configure the Claims Issuer to be Auth0
                options.ClaimsIssuer = "Auth0";
            });
           ...
```

Here is the `project.json` file for the application with insignificant things removed:
```
{
  "dependencies": {
    ...
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel.Https":"1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  ...

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "appsettings.Production.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

Looking at the source for `OpenIdConnectOptions`, it is not readily apparent where it is taking the dependency on System.Xml.  We are thinking it might be 
```c#
            CallbackPath = new PathString("/signin-oidc");
            RemoteSignOutPath = new PathString("/signout-oidc");
```
but that is a [SWAG](https://en.wikipedia.org/wiki/Scientific_wild-ass_guess).

**Comment by Eilon** [comment]
@mattbrewer can you share your app on a GitHub repo so we can take a look? Are you deploying to Azure Application Services or to a VM on Azure?

**Comment by mattbrewer** [comment]
@Eilon We are deploying to Azure Application Services.

Currently we have a private repo on VSTS Online.  I will ask the client if they mind that we put the application source into a public Github repo.  We might need to take the offending piece of code and create a sample project.

**Comment by Eilon** [comment]
Closing for now because we don't have enough information to reproduce this. Please re-open if you have more information. Thanks!
