### ISSUE TITLE
Unable to process token

### ISSUE THREAD

**Issue by mlbiam** [aspnet/Security#1045]
I'm writing an identity provider.  It works with mod_auth_openidc (Ping's project for Apache) and Kubernetes.  I'm trying to integrate it with the asp.net core openid connect provider 1.1.  It will trigger an authentication without issue but when it tries to process the access token I get the following error:

```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5266/signin-oidc?code=JctHrptAAADQu3j7I9EHnB0MpjqMAVOMssEw9GIDY0qUu%2BdL2bzd%2B3OqP6efp6CdUEQ7uhqrN%2BqqBgx9YVX5N6FpLv%2Fv6ccJD9m0vxace%2FhN8Lx8v6P3pXiu3yrUtbsJxfHL9Z6xpO1bOYHUvacWUus8JUrGdTQYVCpfLpk9Amas6dQ%2FP7HbXUNWUY57P7ppqx%2FfRtBWRypsHh6EevpABC4PIov1Ej%2BCbCScofotq3DO13TvZcfVuPng6B4lkjN5j5f4Omr%2F%2FBGK8sYFfnE0djBRVN%2Fn8r49iqXCkOdV2qqqLaMizjHCbWOXei%2BWF90DF29a3l9gW8iDJjUTafE4BeAQ3gEprreqNMbb6kiHQuTXkDRD7t6AUQsB6gLvjMYu7yAtklGNs6%2FqEju9p0tTcAEr6rb0rZ%2Bp1dDjis1llpmihDSwGNNVBJteCWEOBWO28TKdqV38pElIGVVcrqbpzqO%2BeHTrMQZSJL5C5hL5Sp4jdOHhqtzKer1ziPeZsKcg%2B3T3Zew2bBUwP9O9eBCIqVA9huz9jBJldud9X94xN5cU3O61ucfdqy0kTTiS95DeBLe0N8oZ2qTwrDExfU41BcwyXKChKt61sX1KmcwWgCc3hgkRP60tp2DAsJa9snpMWddIa2kezI7qtuFc%2BVftMO2KGNhTeoYLAZGp2eubYrWA%2BOvi2T6nlEID0CIpvW61Ilh1V8HY%2FSB%2F1UD8oJWViC0a9Ofg7%2BGyptln2i2WaaLjw5PT338%3D&state=CfDJ8ImJlfIQfUZGtC0SyBUvDQTNMzpjQ4bilzj58KJyHkgBnwldL5GuAFHaK7R39iEDNi3q2WbDxxLTWy7YfpDdpn3WCgE36Q5F6ZTSeilItpcvrMP27TccKYiX2XquQrlLKS2cqoOof0jyn1E7gaCJ7hEeiC8uFbgMSaEVmfBPQEIk6IA6tFuB_QAH7lmDGFB0o1GyIgJo_ypRe-pklRuvg2HaN_aVyseoQj4MKQh1QmfSitwLwdQ2edtpeZN5HO5YxSbD2nf6uwxY5Hw9wa-5bxvU_LA9jZ9dMd6ckIe0X62ctC9O_FeLH5AGdicAgVVXa1FRtWwU4CvJoY7Z0fIA_Q-y0n1LdhuX303yJo9c9nzGih5DRXl0K2UjSpZBpfyNlA  
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware:Error: Exception occurred while processing message.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<GetUserInformationAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__20.MoveNext()
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware:Information: Error from RemoteAuthentication: Object reference not set to an instance of an object..
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

System.AggregateException: Unhandled remote failure. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<GetUserInformationAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<GetUserInformationAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__20.MoveNext()<---
```

Here's the access token returned from the code token exchange:
```
{"access_token":"eyJraWQiOiJDTj1vaWRjLXNpZywgT1U9dGVzdCwgTz10ZXN0LCBMPXRlc3QsIFNUPXRlc3QsIEM9dGVzdC1DTj1vaWRjLXNpZywgT1U9dGVzdCwgTz10ZXN0LCBMPXRlc3QsIFNUPXRlc3QsIEM9dGVzdC0xNDc5MjA1NTU3MDg4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoiZG90bmV0bG9jYWwiLCJleHAiOjE0Nzk3NjM2ODgsImp0aSI6Il9hSG1jSDBBS3B1VTJKSnJYaWF1d1EiLCJpYXQiOjE0Nzk3NjM2MjgsIm5iZiI6MTQ3OTc2MzU2OCwibm9uY2UiOiI2MzYxNTM2MDQyODIxNDk0NDMuTkdZelptRXhNakF0WWpabU5pMDBZVEkwTFdGallXUXRNVGt5WVdZMVpqSmlZbVpqT1RJMU0yWTRaVE10TmpNNFlTMDBOamcxTFdFek16UXRZV0poT1dObVltUm1PVFpoIiwic3ViIjoibW1vc2xleSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImZpcnN0X25hbWUiOiJNYXR0IiwiZmFtaWx5X25hbWUiOiJNb3NsZXkiLCJlbWFpbCI6Im1hdHQubW9zbGV5QHRyZW1vbG9zZWN1cml0eS10ZXN0LmNvbSJ9.OzTf-UWFkKkSjc5ME_51B7yFM7v5Nte4bKrgxt3w7F_9D3b_ObdCR6KncSKjsKfecwpce8jMsDf5QiTXWYxC3JRsJheh_R0Y5p5xADalhlv7fTRu1qKFs25Ezv0wPhAGedwQhFCAEQZNrUe5zw6_PIUNGslDioTXBmmjZxV_vzV6dX6LqUTn-AGp6Ah0fnLzpRrkldbAqPJJepVtJ_Z8_J7RPWLBnsrw-p2eBU0CcW5yrxYiw-CGbAqbU8rrPPD_UwS6PbtHoWqT0hz82t70j_A84sv5Zvo31ygsklrRVnL9M8-WAwT1i0BaqAZR2AJgLpRbZQVZnxuiDhG7HrQ7vg","expires_in":60,"token_type":"Bearer","id_token":"eyJraWQiOiJDTj1vaWRjLXNpZywgT1U9dGVzdCwgTz10ZXN0LCBMPXRlc3QsIFNUPXRlc3QsIEM9dGVzdC1DTj1vaWRjLXNpZywgT1U9dGVzdCwgTz10ZXN0LCBMPXRlc3QsIFNUPXRlc3QsIEM9dGVzdC0xNDc5MjA1NTU3MDg4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoiZG90bmV0bG9jYWwiLCJleHAiOjE0Nzk3NjM2ODgsImp0aSI6Ims5V1pHTVU1Tm9vLW15TXZuVGNqdmciLCJpYXQiOjE0Nzk3NjM2MjgsIm5iZiI6MTQ3OTc2MzU2OCwibm9uY2UiOiI2MzYxNTM2MDQyODIxNDk0NDMuTkdZelptRXhNakF0WWpabU5pMDBZVEkwTFdGallXUXRNVGt5WVdZMVpqSmlZbVpqT1RJMU0yWTRaVE10TmpNNFlTMDBOamcxTFdFek16UXRZV0poT1dObVltUm1PVFpoIiwic3ViIjoibW1vc2xleSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImZpcnN0X25hbWUiOiJNYXR0IiwiZmFtaWx5X25hbWUiOiJNb3NsZXkiLCJlbWFpbCI6Im1hdHQubW9zbGV5QHRyZW1vbG9zZWN1cml0eS10ZXN0LmNvbSJ9.GFGkY4lYD7yF6lZ1RhpG87E9OUJ8BdmN7XlT0uFhPpRpS_wajToqme3RxuGWnDWruRO2OipjG8qj3MWEHyPBPCUEKKOWsTvcxiXgFl9x1XZtaLqu3aW6UI7j2tfUxzmy5WpG8-zuzp704nBBxxUJ6tZcqACFIOGoKDuYCkHmEtLIPNp077wL_L8VKG--ZG1Ds-Zv7GzXzcXTdGs00oP2NpLT7HVYT-R5P-u62t5fgNffHTTtultw7XAQFHqix_BBvWac0VsG1Qok8LD4tIahUReo7ULYKKIUB-u6kVw4AR3VNtVW9wk59gXbg2Kb2udkZ8CfOcQ9tYZD8dr53y2LFw","refresh_token":"q1bKLFOyUvI1NQh3qvIMMcxPKvFKDqlISUvUL06PKTUwME6BkEo6Sql5yUWVBSWpKUGphaWpxSVAfcG+LiVpZYE5xcURaRFFhW7ZQQEWLiXJUVnhkW4mblHpySGlLlnafomOIQYVTmll5v6OxtrePqnu+Y5BETlZFX5KtQA\u003d"}
```

here's the output of the provider:
```
{
  "issuer": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP",
  "authorization_endpoint": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/auth",
  "token_endpoint": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/token",
  "userinfo_endpoint": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/userinfo",
  "revocation_endpoint": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/revoke",
  "jwks_uri": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/certs",
  "response_types_supported": [
    "code",
    "token",
    "id_token",
    "code token",
    "code id_token",
    "token id_token",
    "code token id_token",
    "none"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "profile"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post"
  ],
  "claims_supported": [
    "sub",
    "aud",
    "iss",
    "exp",
    "sub",
    "email_verified",
    "first_name",
    "family_name",
    "email"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

i don't see a MoveNext anywhere in the code.  Am I missing some piece of data?

**Comment by brockallen** [comment]
What does a response from `"jwks_uri": "https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP/certs",` look like?

**Comment by mlbiam** [comment]
@brockallen 

```
{"keys":[{"kty":"RSA","kid":"CN=oidc-sig, OU=test, O=test, L=test, ST=test, C=test-CN=oidc-sig, OU=test, O=test, L=test, ST=test, C=test-1479205557088","use":"sig","alg":"RS256","n":"hm1LTDy95eJfDLag27sfBHDZ3ZJqSKHOYOrL2lg2XzXD2CxCXdZwmw9dduArLuvxlwe2RDqXxqD9biURda3rmu9myl6IefRcBuG4v2ojq-dXotnPZ6B8NG_GXF--3MflxPx4LXyx1PHSjjcQ_4Bifym_ck0879_W5E27VWhKC0vue7f8njEWpBTdLVwz_sha9aM8vGahIJEYxefeHKGjEoDrHZq59AvhiBq_xPIukxMg9IA4ZOAYNE2svdNxiDENq9CU6qQWneCnZ6R2kiZuU-tFOqUwDuLd7qymmskAZfMrH68EQj5-GMa2OlcNKH4qaURrBVyzE3HivEpna3Xn6w","e":"AQAB"}]}
```

**Comment by mlbiam** [comment]
@brockallen its actually never calling the userinfo endpoint.  It calls /token then fails

**Comment by Tratcher** [comment]
If the user-info request isn't sent then the null ref is coming from this range:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L758-L775

There are very few things that could null-ref there. One way to debug this is to checkout the Security code (rel or master branch) and add a global.json reference to it in your repo. Then you can put a break point  in the linked method and see what's null.

**Comment by brockallen** [comment]
Perhaps this issue illustrates that there could be more logging here.

**Comment by mlbiam** [comment]
PRBKAC - I had implemented userinfo as post instead of get.  Once I added the source to my project and set some break points this became obvious.

great library, very easy to get everything working!

**Comment by Tratcher** [comment]
What line caused the null ref? That shouldn't happen regardless of the response.
