### ISSUE TITLE
Very weird issue, one machine (out of many) unable to match "kid"

### ISSUE THREAD

**Issue by brphelps** [aspnet/Security#1064]
I'm stumped, so I figured an issue was a good place to start. We UseJwtBearerAuthentication to configure our ASP Core 5 app, and generally have been doing so without a hitch so far. Our deployed environments and local environments are able to validate tokens, at least, until we got a new hire. This new hire's machine seems to be giving validation errors where other machines (including PROD machines) are not. 

This is the error we see:

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': 'RrQqu9rydBVRWmcocuXUb20HGRM', 

   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()

Is there anything on the ASP NetCore side that would contribute to this? As you might imagine from the call stack, we're relying on .Net 4.6.2 to actually provide the CLR implementation to us. The weirdest part about this error is that it seems to only be specific to his machine, which blows my mind (this is validating AAD tokens pretty much out of the box).

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#545
