### ISSUE TITLE
Problem with using JWE with symmetric key and A128CBC_HS256 encryption.

### ISSUE THREAD

**Issue by rafsawicki** [aspnet/Security#1332]
I am not able to use `UseJwtBearerAuthentication` middleware to authenticate using JWE. I am receiving an error that JWT is not well formed. If I switch to non encrypted tokens then everything works correctly, but that is not feasible for my use case.

I generate simplest possible token using jose-jwt library:
```csharp
var payload = new Dictionary<string, object>()
{
	{ "sub", "mr.x@contoso.com" },
	{ "exp", 1514678400 }
};
var secretKey = Convert.FromBase64String("n2zLQ28jajGaWcqwjE1dtEixUzrBrw0bQSIEh3fQRDs=");
var token = JWT.Encode(payload, secretKey, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);
```
Which generates the following token:
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..dVCtH0JkXmtICXXV94zvzQ.WC7VdNtmJ23EH8Mq1wgjK9zbJZsK2-Jtxh76sxVyk1G11_lk6yA4ULcpg2BmdEv5.hS1dlr5mq7gUHivIot-VrA
```
Then, I set up Jwt authentication:
```csharp
var tokenValidationParameters = new TokenValidationParameters
{
    ValidateIssuerSigningKey = false,
    TokenDecryptionKey = new SymmetricSecurityKey(Convert.FromBase64String("n2zLQ28jajGaWcqwjE1dtEixUzrBrw0bQSIEh3fQRDs=")),
    ValidateIssuer = false,
    ValidateAudience = false,
    ValidateLifetime = false,
    RequireExpirationTime = false,
    ClockSkew = TimeSpan.Zero,
};

app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    TokenValidationParameters = tokenValidationParameters
});
```
And secure all API endpoints
```csharp
services.AddMvc(options =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
});
```

If I now try to make request to any API endpoint I receive the following error:
```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[1]
      Failed to validate the token eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..dVCtH0JkXmtICXXV94zvzQ.WC7VdNtmJ23EH8Mq1wgjK9zbJZsK2-Jtxh76sxVyk1G11_lk6yA4ULcpg2BmdEv5.hS1dlr5mq7gUHivIot-VrA.
System.ArgumentException: IDX10709: JWT is not well formed: '{"sub":"mr.x@contoso.com","exp":1514678400}'.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
      Bearer was not authenticated. Failure message: IDX10709: JWT is not well formed: '{"sub":"mr.x@contoso.com","exp":1514678400}'.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
```
So from logs it looks like that token is decoded correctly, as it's possible to see payload that was sent, but validation is still failing. Is there anything obvious that I'm missing?

I'm using Microsoft.AspNetCore.Authentication.JwtBearer 1.1.2 package.

**Comment by Tratcher** [comment]
@brentschmaltz ?

**Comment by brentschmaltz** [comment]
@rafsawicki @Tratcher the IdentityModel library is expecting the inner token to be a signed JWT (JWS). 
We currently don't handle just JSON as the inner bits. We are adding an extension to our 5.2.0 release that will give you control in handling the inner token.

**Comment by rsawicki-neurosys** [comment]
I can confirm that signing and then encrypting token solves the problem that I have. Thank you.

**Comment by nikitaulshin** [comment]
Hello everyone!

I faced the same problem, could somebody please provide a small example of signing -> encrypting tokens?

**Comment by rafsawicki** [comment]
@nikitaulshin 
You need to encrypt a signed token. Right now you're not using `signedToken` variable at all, you're encrypting an original payload. It should be something along the lines of
```csharp
return JWT.Encode(signedToken, encryptionKey, JweAlgorithm.A256KW, JweEncryption.A128CBC_HS256);
```
In my use case, I was using `JweAlgorithm.DIR` - it's the simplest one with the same key for encryption and decryption. You can try using it instead of `JweAlgorithm.A256KW` if you run into any more issues.
