### ISSUE TITLE
Twitter Authentication doesn't work as described in docs

### ISSUE THREAD

**Issue by tabakerov** [aspnet/Security#1662]
I'm following [this](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?tabs=aspnetcore2x) tutorial. 
I have created new ASP.NET Core MVC app (VS2017 15.5.6, targeting .NET Core 2.0, based on Microsoft.AspNetCore.All v2.0.5) then added Microsoft.AspNetCore.Authentication.Twitter (v 2.0.1).
I added

```
services.AddAuthentication().AddTwitter(options =>
{
options.ConsumerKey = "8QTUn... CONSUMER KEY";
options.ConsumerSecret = "mhJvQ5liYQ... CONSUMER SECRET";
});
```

to Startup.cs just after 

```
services.AddIdentity<ApplicationUser, IdentityRole>()
.AddEntityFrameworkStores<ApplicationDbContext>()
.AddDefaultTokenProviders();

```
lines.
When I run and try login with Twitter I'm getting 

```
An unhandled exception occurred while processing the request.
HttpRequestException: Response status code does not indicate success: 401 (Authorization Required).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```

**Comment by tabakerov** [comment]
trying to debug the issue I get this value for Authorization header: `{OAuth oauth_callback="http%3A%2F%2Flocalhost%3A35857%2Fsignin-twitter", oauth_consumer_key="8QTUn...NAF", oauth_nonce="bd89dae721674133b4a58d047be5c22c", oauth_signature="zqesuPmJqUzQ49wpgyvhn8nyN6A%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1519210280", oauth_version="1.0"}`

**Comment by tabakerov** [comment]
@blowdart 
step-0 = Ok
step-1 with my ConsumerKey & ConsumerSecret = 
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLBRQ5ERRSD5", Request id "0HLBRQ5ERRSD5:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Authorization Required).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler.<ObtainRequestTokenAsync>d__14.MoveNext()
```

**Comment by tabakerov** [comment]
Oh, the issue was because of typo in Callback URL!
Thanks!
