### ISSUE TITLE
Openid Connect and Google App Engine Flexible Env - Correlation Failed

### ISSUE THREAD

**Issue by alex-birch** [aspnet/Security#1699]
I get a correlation failed stack when I configure Google App Engine (GAE) Flex Env to have more than 1 instance serving my dotnet core 2.0 aspnet application.

It works perfectly when I restrict GAE to _**exactly**_ 1 instance serving. It seems that I need to configure dot net core auth to work in a web farm, but can't find documentation on how to do so. The classic ASPNET core uses machine key in web.config - is it the same for dotnet core 2.0? Right now I get the stack trace shown at the end of the lodged issue.

I think GAE and Flex env is really NGINX serving to Kestrel.

Some more info about my setup:
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5"/>
<PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.0.3"/>
<PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.0.2"/>
```
```
services.AddCookie(options => 
            {
                options.LoginPath = "/account/signin";
                options.LogoutPath = "/account/signout";
                options.AccessDeniedPath = "/Home/Forbidden";
                options.SlidingExpiration = true;
                options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
                options.Events.OnRedirectToLogin = context =>
                {
                    context.Response.Headers["Location"] = context.RedirectUri;
                    context.Response.StatusCode = 401;
                    return Task.CompletedTask;
                };
            })
            .AddOpenIdConnect(options => 
            {
                JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
                options.Authority =  "https://accounts.google.com/";
                options.ClientId = settings.OAuthSettings.GoogleOAuthSettings.ClientId;
                options.ClientSecret = settings.OAuthSettings.GoogleOAuthSettings.ClientSecret;
                options.SaveTokens = true;
                options.Scope.Add("email");

                options.ClaimActions.Clear();
                options.ClaimActions.MapJsonKey(ClaimTypes.Email, "email", ClaimValueTypes.Email); 
                options.ClaimActions.MapJsonKey("hd", "hd");
                options.GetClaimsFromUserInfoEndpoint = true;
                options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = context =>
                    {
                        if (context.Request.Path != "/account/google")
                        {
                            context.Response.Redirect("/account/signin");
                            context.HandleResponse();
                        }
                        context.ProtocolMessage.SetParameter("prompt", "select_account");
                        return Task.FromResult(0);
                    },
                };
            });

// forwarded headers (as we're behind a reverse proxy)
var forwardingOpts = new ForwardedHeadersOptions
{
        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
        RequireHeaderSymmetry = false,
};
forwardingOpts.KnownNetworks.Clear();
forwardingOpts.KnownProxies.Clear();
app.UseForwardedHeaders(forwardingOpts);

```
And the stack trace I get:
```
System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
Microsoft.AspNetCore.Server.Kestrel[13]
=> RequestId:0HLCE2O4II2KI:00000004 RequestPath:/signin-oidc => RequestId:0HLCE2O4II2KI:00000004 RequestPath:/signin-oidc
Connection id "0HLCE2O4II2KI", Request id "0HLCE2O4II2KI:00000004": An unhandled exception was thrown by the application.
System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

Reiterating - it works perfectly when only 1 kestrel server is serving. When there is more than 1, some of the requests work, the others get the above exception and a 401 HTTP status.

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by alex-birch** [comment]
Thanks @Tratcher 

For completeness - I got this up and running using the following code:

```
var redis = ConnectionMultiplexer.Connect(redisHost);
services.AddDataProtection()
              .SetApplicationName("shared app name")
              .PersistKeysToRedis(redis, "DataProtection-Keys");
```

This *doesn't* encrypt the keys in redis - but was acceptable for me. GCloud at the moment doesn't natively support Redis - so that needed to be custom instance on their compute machine.

**Comment by WeihanLi** [comment]
This really helps me. Thank you.

**Comment by WeihanLi** [comment]
It works great for me.But I can not understand why I have to use the `DataProtection`? 
It works well for one instance without it,why it will be a problem for more than one instance?
Hope for reply.Thank you.

**Comment by WeihanLi** [comment]
How does it protects data in the login flow in one instance without `DataProtect` ?

**Comment by Tratcher** [comment]
Data protection has defaults that work on a single machine.

**Comment by WeihanLi** [comment]
Why not more than one? How does it work then?
