### ISSUE TITLE
WsFederation SecurityTokenInvalidSignatureException throw even ValidateIssuerSigningKey is false

### ISSUE THREAD

**Issue by mgolois** [aspnet/Security#1714]
Hello,

My app is using wsFederation and I'm trying to bypass signature verification for dev/debug envionment.

```c#
 public void ConfigureServices(IServiceCollection services)
{
            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;

            }) .AddWsFederation(options =>
            {
                options.Wtrealm = "xxxxxxxxxxx";
                options.MetadataAddress = "https://xxxxxxx.com/FederationMetadata.xml";
                options.RequireHttpsMetadata = false;
                options.TokenValidationParameters.ValidateIssuerSigningKey = false;
                options.TokenValidationParameters.ValidateActor = false;
                options.TokenValidationParameters.ValidateAudience = false;
                options.TokenValidationParameters.ValidateIssuer = false;
                options.TokenValidationParameters.ValidateLifetime = false;
                options.TokenValidationParameters.ValidateTokenReplay = false;
                options.CallbackPath = "/Home/Index";
            })
            .AddCookie();
}

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseAuthentication();
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }
            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

Here is the error I get:
```
fail: Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler[3]
      Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: XXXXXXXXXXXXXXX
'.
Exceptions caught:
 'Microsoft.IdentityModel.Xml.XmlValidationException: IDX30207: SignatureMethod is not supported: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'. CryptoProviderFactory: 'Microsoft.IdentityModel.Tokens.CryptoProviderFactory'.
   at Microsoft.IdentityModel.Xml.Signature.Verify(SecurityKey key, CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: 'Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken'.
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleRemoteAuthenticateAsync>d__9.MoveNext()
info: Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler[4]
      Error from RemoteAuthentication: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: 2EE148D651630AACC591C806B5A5370090671F5A
      '.
Exceptions caught:
 'Microsoft.IdentityModel.Xml.XmlValidationException: IDX30207: SignatureMethod is not supported: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'. CryptoProviderFactory: 'Microsoft.IdentityModel.Tokens.CryptoProviderFactory'.
         at Microsoft.IdentityModel.Xml.Signature.Verify(SecurityKey key, CryptoProviderFactory cryptoProviderFactory)
         at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
      '.
token: 'Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken'..
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCOP6FQE4O0", Request id "0HLCOP6FQE4O0:00000002": An unhandled exception was thrown by the application.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: XXXXXXXXXXXXXXX
'.
Exceptions caught:
 'Microsoft.IdentityModel.Xml.XmlValidationException: IDX30207: SignatureMethod is not supported: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'. CryptoProviderFactory: 'Microsoft.IdentityModel.Tokens.CryptoProviderFactory'.
   at Microsoft.IdentityModel.Xml.Signature.Verify(SecurityKey key, CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: 'Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken'.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 299.5734ms 500
```

**Comment by Tratcher** [comment]
The token is using a sha1 signature which is obsolete. 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/275

@brentschmaltz should they be able to bypass this validation?

**Comment by brentschmaltz** [comment]
@Tratcher one could use extensibility to hook a CustomCryptoProviderFactory.
TokenValidationParameters.CryptoProviderFactory.

I just added a sample here on how to use KeyVault for signing a SAML token. 
This should give some idea.

https://github.com/brentschmaltz/IdentityModel/blob/master/Samples/KeyVaultExtensions/KeyVaultCryptoProviderFactory.cs#L13

**Comment by petersladek** [comment]
For SAML tokens using SHA1 signatures there is one implementation over here https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/973#issuecomment-418359214
