### ISSUE TITLE
AuthorizationPolicyBuilder ArgumentNullException when using a PolicyProvider

### ISSUE THREAD

**Issue by nrandell** [aspnet/Security#1764]
I've got a situation where I'm trying to use an IAuthorizationPolicyProvider to provide a policy for the logged in user.

However I keep seeing ArgumentNullException in Authorizationpolicybuilder.Combine

```
System.ArgumentNullException: Value cannot be null.
Parameter name: policy
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder.Combine(AuthorizationPolicy policy)
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder..ctor(AuthorizationPolicy policy)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.GetEffectivePolicyAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

As far as I can tell, the issue is caused in `GetEffectivePolicyAsync`

As the filter was created using an `IAuthorizationPolicyProvider`, Policy is null.
When it comes to combining filters, a new `AuthorizationPolicyBuilder` is constructed using the Policy (assigned to effectivePolicy). `effectivePolicy` is null, so the `AuthorizationPolicyBuilder` throws.

Am I doing something wrong, or is this a bug?

All using 2.1.0-rc1

**Comment by HaoK** [comment]
This looks like a bug/regression I think, I'll investigate

**Comment by HaoK** [comment]
In the short term as a workaround, can you try turning AllowCombiningAuthorizeFilters = false in mvcOptions?

**Comment by nrandell** [comment]
Yes - that worked ok.

**Comment by HaoK** [comment]
This is a dupe of https://github.com/aspnet/Mvc/issues/7809
