### ISSUE TITLE
Setting up Google authentication with multiple instances of web app

### ISSUE THREAD

**Issue by agr** [aspnet/Security#1805]
I have an ASP.NET Core 2.1 web app that uses Google authentication. Authentication bits work fine on dev machine but I was getting the following exception when moved to actual production environment:

```
 info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
       Request starting HTTP/1.1 GET http://hostname/signin-google?state=staaaate&code=cooooode&authuser=0&session_state=another_state&prompt=none
 info: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[4]
       Error from RemoteAuthentication: The oauth state was missing or invalid..
 fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
       An unhandled exception has occurred while executing the request.
 System.Exception: An error was encountered while handling the remote login. ---> System.Exception: The oauth state was missing or invalid.
    --- End of inner exception stack trace ---
    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Took me a while to realize that it's happening because prod have two instances of the app running and the reverse proxy in front of it set up to round robin between two instances. So the request to log in is received by one instance (and it responds with redirect to Google for auth) and Google's post authentication redirect is received by another instance which apparently does not expect to see it.

So, I'd guess, the instance that starts authentication persists some sort of state somewhere which another instance lacks. For now I sorted it out by setting up proxy to post requests coming from one IP to the same backend instance, instead of going round robin.

What is the proper solution to it? How do I make any instance able to receive and properly handle authentication callback?

App is running on Linux with nginx as a reverse proxy.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Docs/issues/3255. For your case specifically you need to configure DataProtection.
