### ISSUE TITLE
Is there a way to Decrypt  encrypted SAML token??

### ISSUE THREAD

**Issue by amitsharma2912** [aspnet/Security#1904]
IDX30011: Unable to read XML. Expecting XmlReader to be at ns.element: 'urn:oasis:names:tc:SAML:1.0:assertion.Assertion', found: 'http://www.w3.org/2001/04/xmlenc#.EncryptedData'.  

 at Microsoft.IdentityModel.Xml.XmlUtil.CheckReaderOnEntry(XmlReader reader, String element, String namespace)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSerializer.ReadAssertion(XmlReader reader)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ReadSamlToken(String token)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at AspNetCoreWsFederation.MyTokenValidator.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in C:\Users\asharma\Downloads\IdentityServer4.WsFederation-dev1\IdentityServer4.WsFederation-dev\src\AspNetCoreWsFederation\MyTokenValidator.cs:line 42
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleRemoteAuthenticateAsync>d__9.MoveNext()

**Comment by blowdart** [comment]
@brentschmaltz ?

**Comment by rasitha1** [comment]
Looks like [SamlSecurityTokenHandler.ValidateToken](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/236bf92594832bc6393aa9f34be3a0dc370bae8b/src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs#L1111) is expecting a plain text token(?). It doesn't seem to have any decryption support.

Maybe you have to override that and provide your own decryption? Looking at how [JwtSecurityTokenHandler](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7692d12e49a947f68a44cd3abc040d0c241376e6/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L692) is implemented, [CryptoProviderFactory](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7692d12e49a947f68a44cd3abc040d0c241376e6/src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs#L40) might help... just a wild guess.

**Comment by brentschmaltz** [comment]
@blowdart @amitsharma2912 @rasitha1 we only support signed saml tokens in 5.3.0.
@GeoK is working on allowing encrypted tokens.

**Comment by blowdart** [comment]
As this is currently "by design", or really "we don't support this yet", I'm closing the issue.

**Comment by amitsharma2912** [comment]
Any idea when this functionality will be available ??? What else can i do to support this for now??
As this is the only functionality hindering our migration.

**Comment by Tratcher** [comment]
@amitsharma2912 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/ is a better place for that question, that's where the implementation will happen.
