### ISSUE TITLE
OpenIdConnect is broken on coreclr due to token validation issues

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#200]
On Coreclr token validation fails with the following error: 
```
An unhandled exception occurred while processing the request.

ArgumentException: Value was invalid.

System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)

SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 92B88C3DD981BF1EBCB244FCFA63C007706C79E0
 System.IdentityModel.Tokens.RsaSecurityKey
 System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 3270BF5597004DF339A4E62224731B6BD82810A6
 System.IdentityModel.Tokens.RsaSecurityKey
 '.
 Exceptions caught:
 'System.ArgumentException: Value was invalid.
 at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, HashAlgorithm hash, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentException: Value was invalid.
 at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentException: Value was invalid.
 at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, HashAlgorithm hash, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentException: Value was invalid.
 at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 '.
 token: '{"typ":"JWT","alg":"RS256","x5t":"MnC_VZcATfM5pOYiJHMba9goEKY"}.{"aud":"62d49e6b-2cd1-42db-abde-d6697d09b82a","iss":"https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/","iat":1427303623,"nbf":1427303623,"exp":1427307523,"ver":"1.0","tid":"72f988bf-86f1-41af-91ab-2d7cd011db47","amr":["wia"],"oid":"56b7170c-8f9b-4a07-8f12-41cabd031456","upn":"prabht@microsoft.com","sub":"TFBR4hfMp9Kjz6isEzWscfaFKrnlhltkkeY_Te_Z0eA","given_name":"Praburaj","family_name":"Thiagarajan","name":"Praburaj Thiagarajan","unique_name":"prabht@microsoft.com","nonce":"635629007156940862.NWYwMmZkYzgtMDQ0My00MGE5LWJhMzAtOWIzZGNhYWM1MWQ2Yjc4N2YyZmQtMjliZC00MWVjLWJlMWEtODg4ZmIwMmE4MzQ5","c_hash":"CVLswooSzsdqwqGoiRoW8A","pwd_exp":"27477708","pwd_url":"https://portal.microsoftonline.com/ChangePassword.aspx"}
 RawData: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiI2MmQ0OWU2Yi0yY2QxLTQyZGItYWJkZS1kNjY5N2QwOWI4MmEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNDI3MzAzNjIzLCJuYmYiOjE0MjczMDM2MjMsImV4cCI6MTQyNzMwNzUyMywidmVyIjoiMS4wIiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwiYW1yIjpbIndpYSJdLCJvaWQiOiI1NmI3MTcwYy04ZjliLTRhMDctOGYxMi00MWNhYmQwMzE0NTYiLCJ1cG4iOiJwcmFiaHRAbWljcm9zb2Z0LmNvbSIsInN1YiI6IlRGQlI0aGZNcDlLano2aXNFeldzY2ZhRktybmxobHRra2VZX1RlX1owZUEiLCJnaXZlbl9uYW1lIjoiUHJhYnVyYWoiLCJmYW1pbHlfbmFtZSI6IlRoaWFnYXJhamFuIiwibmFtZSI6IlByYWJ1cmFqIFRoaWFnYXJhamFuIiwidW5pcXVlX25hbWUiOiJwcmFiaHRAbWljcm9zb2Z0LmNvbSIsIm5vbmNlIjoiNjM1NjI5MDA3MTU2OTQwODYyLk5XWXdNbVprWXpndE1EUTBNeTAwTUdFNUxXSmhNekF0T1dJelpHTmhZV00xTVdRMllqYzROMll5Wm1RdE1qbGlaQzAwTVdWakxXSmxNV0V0T0RnNFptSXdNbUU0TXpRNSIsImNfaGFzaCI6IkNWTHN3b29TenNkcXdxR29pUm9XOEEiLCJwd2RfZXhwIjoiMjc0Nzc3MDgiLCJwd2RfdXJsIjoiaHR0cHM6Ly9wb3J0YWwubWljcm9zb2Z0b25saW5lLmNvbS9DaGFuZ2VQYXNzd29yZC5hc3B4In0.bNALjrvoF_WMzwAuLlrxu7xUJo39M0EQNX91XHQw0hldt7WIHxFa-4FSxWj6tBj8YwClcyHpbvs_r9YlosmHre-MX7PEIe9gy_N2B6-9Ax9MlQESjF1KxJsBY1eFwx410HJUtBZI8wCvkVI5rU1cUpRnKSqc8B8LX8yl5DjvOK7DLHVbxIqXQ_1dBozcsSHX7kTSy9C0yzeSyM0YhodHlHV2O8BQbOf0pEeIgHyDz97P3UOM-FSEaUvTQTYW3URzK5-YyeWl5OaXe-mpv5UvxwArlzC19p9E3Xp8zEHt1zAAPxrHR4n-QVj-5JXB8k96R8E1WEQOP980xr_FY7PlRg'

System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 Stack 
  Query 
  Cookies 
  Headers 
  Environment 
 

ArgumentException: Value was invalid.

System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group)


System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)


System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, HashAlgorithm hash, Byte[] signature)


System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)


System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)


System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)



SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 92B88C3DD981BF1EBCB244FCFA63C007706C79E0 System.IdentityModel.Tokens.RsaSecurityKey System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 3270BF5597004DF339A4E62224731B6BD82810A6 System.IdentityModel.Tokens.RsaSecurityKey '. Exceptions caught: 'System.ArgumentException: Value was invalid. at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group) at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature) at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, HashAlgorithm hash, Byte[] signature) at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) System.ArgumentException: Value was invalid. at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group) at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature) at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) System.ArgumentException: Value was invalid. at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group) at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature) at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, HashAlgorithm hash, Byte[] signature) at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) System.ArgumentException: Value was invalid. at System.Security.Cryptography.Utils.ObjToAlgId(Object hashAlg, OidGroup group) at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature) at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm) at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) '. token: <Full Jwt token here.> 
RawData: {RawDatagoeshere.}'

System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)


System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken)


Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__12.MoveNext()


```

**Comment by Praburaj** [comment]
@brentschmaltz @tushargupta51 @muratg

**Comment by tushargupta51** [comment]
looking into it.

**Comment by muratg** [comment]
@tushargupta51 any updates on this? If you want to fix this, we'll need to have a PR soon (and also email Dan & Eilon to ask if you can check-in, but @Praburaj can do that)

**Comment by muratg** [comment]
FYI /cc @Eilon @danroth27

**Comment by Praburaj** [comment]
@muratg I guess the fix for this bug will be in Wilson. The middleware should automatically work when that's fixed. I filed a bug here as this is a better place to track.

**Comment by muratg** [comment]
Cool, so no code change in this repo then.

**Comment by Praburaj** [comment]
yeah. that's right.

**Comment by Praburaj** [comment]
This is fixed now.
