### ISSUE TITLE
OpenId connect fails with SecurityTokenInvalidSignatureException on latest coreclr 

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#223]
```
[12:16:17][xunit-test]         <h1>An unhandled exception occurred while processing the request.</h1>
[12:16:17][xunit-test]                 <div class="titleerror">SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: &#x27;System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 92B88C3DD981BF1EBCB244FCFA63C007706C79E0<br />
[12:16:17][xunit-test] System.IdentityModel.Tokens.RsaSecurityKey<br />
[12:16:17][xunit-test] System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 3270BF5597004DF339A4E62224731B6BD82810A6<br />
[12:16:17][xunit-test] System.IdentityModel.Tokens.RsaSecurityKey<br />
[12:16:17][xunit-test] &#x27;.<br />
[12:16:17][xunit-test] Exceptions caught:<br />
[12:16:17][xunit-test]  &#x27;System.ArgumentNullException: Value cannot be null.<br />
[12:16:17][xunit-test] Parameter name: SafeHandle cannot be null.<br />
[12:16:17][xunit-test]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp; success)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle&amp; phHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, Object hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)<br />
[12:16:17][xunit-test] System.ArgumentNullException: Value cannot be null.<br />
[12:16:17][xunit-test] Parameter name: SafeHandle cannot be null.<br />
[12:16:17][xunit-test]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp; success)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle&amp; phHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)<br />
[12:16:17][xunit-test] System.ArgumentNullException: Value cannot be null.<br />
[12:16:17][xunit-test] Parameter name: SafeHandle cannot be null.<br />
[12:16:17][xunit-test]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp; success)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle&amp; phHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, Object hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)<br />
[12:16:17][xunit-test] System.ArgumentNullException: Value cannot be null.<br />
[12:16:17][xunit-test] Parameter name: SafeHandle cannot be null.<br />
[12:16:17][xunit-test]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp; success)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle&amp; phHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)<br />
[12:16:17][xunit-test]    at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)<br />
[12:16:17][xunit-test]    at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)<br />
[12:16:17][xunit-test] &#x27;.<br />
[12:16:17][xunit-test] token: &#x27;{&quot;typ&quot;:&quot;JWT&quot;,&quot;alg&quot;:&quot;RS256&quot;,&quot;x5t&quot;:&quot;kriMPdmBvx68skT8-mPAB3BseeA&quot;}.{&quot;aud&quot;:&quot;c99497aa-3ee2-4707-b8a8-c33f51323fef&quot;,&quot;iss&quot;:&quot;https://sts.windows.net/4afbc689-805b-48cf-a24c-d4aa3248a248/&quot;,&quot;iat&quot;:1422395763,&quot;nbf&quot;:1422395763,&quot;exp&quot;:1422399663,&quot;ver&quot;:&quot;1.0&quot;,&quot;tid&quot;:&quot;4afbc689-805b-48cf-a24c-d4aa3248a248&quot;,&quot;amr&quot;:[&quot;pwd&quot;],&quot;oid&quot;:&quot;f876abeb-d6b5-44e4-9716-6266ac0181a8&quot;,&quot;upn&quot;:&quot;user3@testgmail.onmicrosoft.com&quot;,&quot;sub&quot;:&quot;PUdhclP5PgIjSU9P1S-HelDaSFSf-mXV1Y60-K2vWqw&quot;,&quot;given_name&quot;:&quot;User3&quot;,&quot;family_name&quot;:&quot;User3&quot;,&quot;name&quot;:&quot;User3&quot;,&quot;unique_name&quot;:&quot;user3@testgmail.onmicrosoft.com&quot;,&quot;nonce&quot;:&quot;635579928639517715.OTRjOTVkM2EtMDRmYS00ZDE3LThhZGUtZWZmZGM4ODkzZGZkMDRlNDhkN2MtOWIwMC00ZmVkLWI5MTItMTUwYmQ4MzdmOWI0&quot;,&quot;c_hash&quot;:&quot;FGt3wcQADe0PY1Qx7O1r6g&quot;,&quot;pwd_exp&quot;:&quot;6693280&quot;,&quot;pwd_url&quot;:&quot;https://portal.microsoftonline.com/ChangePassword.aspx&quot;}&#x27;</div>
[12:16:17][xunit-test]                     <p class="location">Microsoft.IdentityModel.Logging.LogHelper.LogError(String message, Type exceptionType, Boolean throwException)</p>

```

**Comment by Praburaj** [comment]
@Tratcher @tushargupta51 could you guys re-enable this scenario once the bug is fixed? 

https://github.com/aspnet/MusicStore/commit/cedfd88254678dd91190636eaf6e7cdf3ed7475f

**Comment by Praburaj** [comment]
@brentschmaltz

**Comment by Praburaj** [comment]
@suhasj

**Comment by brentschmaltz** [comment]
@Praburaj I was out yesterday.  When did this start happening?

**Comment by brentschmaltz** [comment]
Has the CLR team been contacted? This worked fine before

**Comment by suhasj** [comment]
This started on Jan 21 with `Microsoft.IdentityModel.Protocol.Extensions 2.0.0-beta4-03310920` I am not sure if that package is the reason but bought it up as an FYI

**Comment by PinpointTownes** [comment]
Ding dong. Any progress regarding this issue?

**Comment by brentschmaltz** [comment]
Was on vacation, anyone know of a clean repro?

**Comment by PinpointTownes** [comment]
It depends on what you mean by "clean repro" :smile: 
You should be able to reproduce this issue by trying to validate any JWT token.

(this samples crashes on CoreCLR if you don't use the `UnsafeJwtSecurityTokenHandler` class: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Startup.cs#L205)

**Comment by brentschmaltz** [comment]
thanks

**Comment by brentschmaltz** [comment]
OH my, this is not good. Thanks.

**Comment by PinpointTownes** [comment]
@brentschmaltz no news from the CLR team? :cry:

**Comment by PinpointTownes** [comment]
FYI, a ticket has been opened on **dotnet/corefx** by @bartonjs: https://github.com/dotnet/corefx/issues/1888

**Comment by Eilon** [comment]
@brentschmaltz can you try to repro this? If it's no-repro on the latest bits, close.

**Comment by PinpointTownes** [comment]
@Eilon the ticket on dotnet/corefx has not been closed yet, so I guess it has not been fixed :smile:

**Comment by Eilon** [comment]
From @Tratcher and @HaoK it sounded like the issue that affects us might be fixed, but that's why we want @brentschmaltz to verify it for real.

**Comment by PinpointTownes** [comment]
I just tried with the latest packages, and I still get the same exception.
It shouldn't be long though, the `corefx` ticket was closed a few minutes after my last message :smile:

**Comment by GuardRex** [comment]
Can I ask if my issue is related? Using the following to access AAD ...
```c#
app.UseCookieAuthentication(options => { options.AutomaticAuthentication = true; });
app.UseOpenIdConnectAuthentication(options => {
    options.ClientId = ClientId;
    options.Authority = Authority;
    options.PostLogoutRedirectUri = PostLogoutRedirectUri;
    options.AutomaticAuthentication = true;
    options.Notifications = new OpenIdConnectAuthenticationNotifications {
        AuthenticationFailed = OnAuthenticationFailed
    };
});
```
... works fine under 1.0.0-beta4 clr x86 but failed under 1.0.0-beta6-* coreclr x64 with ...
```
IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 92B88C3DD981BF1EBCB244FCFA63C007706C79E0
 System.IdentityModel.Tokens.RsaSecurityKey
 System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 3270BF5597004DF339A4E62224731B6BD82810A6
 System.IdentityModel.Tokens.RsaSecurityKey
 '. Exceptions caught: 'System.ArgumentNullException: Value cannot be null.
 Parameter name: SafeHandle cannot be null.
 at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
 at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle& phHash)
 at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)
 at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, Object hash, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentNullException: Value cannot be null.
 Parameter name: SafeHandle cannot be null.
 at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
 at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle& phHash)
 at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)
 at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentNullException: Value cannot be null.
 Parameter name: SafeHandle cannot be null.
 at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
 at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle& phHash)
 at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)
 at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy.VerifyData(Byte[] signingInput, Object hash, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 System.ArgumentNullException: Value cannot be null.
 Parameter name: SafeHandle cannot be null.
 at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
 at Internal.NativeCrypto.CapiHelper.Interop.CryptCreateHash(SafeProvHandle hProv, Int32 algId, SafeKeyHandle hKey, CryptCreateHashFlags dwFlags, SafeHashHandle& phHash)
 at Internal.NativeCrypto.CapiHelper.CreateHashHandle(SafeProvHandle hProv, Byte[] hash, Int32 calgHash)
 at Internal.NativeCrypto.CapiHelper.VerifySign(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 calgKey, Int32 calgHash, Byte[] hash, Byte[] signature)
 at System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(Byte[] buffer, Object halg, Byte[] signature)
 at System.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
 at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
 '. token: <TOKEN_DATA_HERE>
```

**Comment by GuardRex** [comment]
Yes ... must be the same issue ... using `UnsafeJwtSecurityTokenHandler` bypassed signature validation.

**Comment by Eilon** [comment]
I think @brentschmaltz is planning to take a look at this today.

**Comment by PinpointTownes** [comment]
Issue fixed :sunglasses:

**Comment by GuardRex** [comment]
I'm still getting this with
```
"Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*"
```
Is this a fix that just went in such that I just need to wait on the next build for MyGet?

**Comment by PinpointTownes** [comment]
You need the latest `System.Security.Cryptography.RSA` package (`4.0.0-beta-23029` works fine on my machine). Also, make sure you have the latest DNX CoreCLR version.

**Comment by GuardRex** [comment]
Ah! I see. Thanks. I was using an older runtime (12081). I'll upgrade and try again.

**Comment by GuardRex** [comment]
@PinpointTownes Went to 12170 ... Fix confirmed here, too. Thanks for the heads up.

**Comment by HaoK** [comment]
Closing since you guys verified things are fixed, thanks!

**Comment by PinpointTownes** [comment]
I suggest reopening this ticket as this bug mysteriously reappeared in `>beta6-12256` and `beta6 release` (but not in the `beta7` bits): https://github.com/dotnet/corefx/issues/1888#issuecomment-126067822

**Comment by GuardRex** [comment]
I can report it seems to be working ok with
```
"Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-beta6-12681"
```

**Comment by PinpointTownes** [comment]
@GuardRex and what's your DNX runtime version?

**Comment by GuardRex** [comment]
@PinpointTownes 1.0.0-beta6-12234

**Comment by GuardRex** [comment]
@PinpointTownes Let me see if I can see if I can repo this with `beta6 release`. brb

**Comment by GuardRex** [comment]
@PinpointTownes No, I'm not seeing it. Seems to be ok with ...
```
dnx-coreclr-win-x64.1.0.0-beta6
```
and
```
"dependencies": {
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta6",
    "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-beta6",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
    "Microsoft.AspNet.Http": "1.0.0-beta6",
    "Microsoft.AspNet.Identity": "3.0.0-beta6",
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6",
    "Microsoft.Framework.ConfigurationModel": "1.0.0-beta5-11337",
    "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.5.207081303-alpha",
    "Microsoft.IdentityModel.Protocol.Extensions": "2.0.0-beta6-207211625",
    "System.Runtime.Serialization.Json": "4.0.0-beta-23110",
    "Microsoft.ApplicationInsights.AspNet":  "1.0.0-beta5"
},
```

**Comment by PinpointTownes** [comment]
That's really weird then... :scream: 

![image](https://cloud.githubusercontent.com/assets/6998306/8972800/9af24a4e-365d-11e5-8b41-76f03ab2ecd9.png)

I'm using the x86 version, but I'll try with the x64 bits.

**Comment by PinpointTownes** [comment]
Same thing with x64:

![image](https://cloud.githubusercontent.com/assets/6998306/8972849/328a7430-365e-11e5-9771-6e975fe61b7f.png)

**Comment by PinpointTownes** [comment]
This bug is really mysterious: https://github.com/dotnet/corefx/issues/1888#issuecomment-126997705
