### ISSUE TITLE
Multiple web servers CookieAuthentication does not work

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/Security#624]
Startup.cs code:

```cs
app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.CookieHttpOnly = true;
    cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
    cookieOptions.LoginPath = new PathString("/account/login");
    cookieOptions.CookieName = ".CNBlogsAdCookie";
    cookieOptions.CookiePath = "/";
});
```

Login code:

```cs
public async Task<IActionResult> Login(string returnUrl = null)
{
    var user = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "xishuai") }, CookieAuthenticationDefaults.AuthenticationScheme));
    await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user, new AuthenticationProperties() { IsPersistent = true });
    return Redirect(returnUrl);
}
```

`"Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc2-16160"`

I publish the site on a single server, it works, but I now use SLB(Server Load Balancer), the site published on two servers, login is not working, how do I solve this problem?

**Comment by Tratcher** [comment]
See http://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html

**Comment by yuezhongxin** [comment]
@Tratcher I read this blog, but my situation is two of the same applications.

**Comment by Tratcher** [comment]
The same approach applies to two instances of the same app. @haok

**Comment by HaoK** [comment]
The main thing you need to do for two apps to share cookies is to have them share the same keys for dataprotection, try something like this:

```
            var dataProtection = new DataProtection.DataProtectionProvider(new DirectoryInfo("<absolutepath to a directory that both apps can see>"));

When configuring cookie Auth:

                    app.UseCookieAuthentication(options => options.DataProtectionProvider = dataProtection);


```

**Comment by yuezhongxin** [comment]
@HaoK I modified the code:

```cs
var dataProtection = new Microsoft.AspNet.DataProtection.DataProtectionProvider(new DirectoryInfo(@"c:\shared-auth-ticket-keys\"));

app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.CookieHttpOnly = true;
    cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
    cookieOptions.LoginPath = new PathString("/account/login");
    cookieOptions.CookieName = ".CNBlogsAdCookie";
    cookieOptions.CookiePath = "/";
    cookieOptions.DataProtectionProvider = dataProtection;
});
```

And I installed this package `"Microsoft.AspNet.DataProtection.Extensions": "1.0.0-rc2-15942"`, but the application can not be started.

This is all my packages:

```json
"dependencies": {
  "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc2-16160",
  "Microsoft.AspNet.DataProtection.Extensions": "1.0.0-rc2-15942",
  "Microsoft.AspNet.Diagnostics": "1.0.0-rc2-16303",
  "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc2-15994",
  "Microsoft.AspNet.Mvc": "6.0.0-rc2-16614",
  "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc2-16614",
  "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-16156",
  "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-16036",
  "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc2-15994",
  "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc2-15905",
  "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-15905",
  "Microsoft.Extensions.Logging": "1.0.0-rc2-15907",
  "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-15907",
  "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-15907",
  "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-16142",
  "Serilog.Framework.Logging": "1.0.0-*"
}
```

**Comment by yuezhongxin** [comment]
I modified the `Microsoft.AspNet.DataProtection.Extensions` version `1.0.0-rc2-15832`, applications can be started, and in the two web servers `c:\shared-auth-ticket-keys\` directory, generates two files:

key-1c672d4e-0ce2-4c0f-95e4-35635be2e021.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<key id="1c672d4e-0ce2-4c0f-95e4-35635be2e021" version="1">
  <creationDate>2015-12-22T03:23:03.8359375Z</creationDate>
  <activationDate>2015-12-22T03:23:03.8046875Z</activationDate>
  <expirationDate>2016-03-21T03:23:03.8046875Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNet.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
        <!-- Warning: the key below is in an unencrypted form. -->
        <value>tjT3oos9WveKk8yZYaEjheMY7RV6LSuwj/l6df7vLyArL2QIG3C0Fy5Aw4WDfoYyrOtrKi4HhbRbDa0NDwE8Xg==</value>
      </masterKey>
    </descriptor>
  </descriptor>
</key>
```

key-847a86d5-33b0-4309-b86b-4e6fee5abea6.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<key id="847a86d5-33b0-4309-b86b-4e6fee5abea6" version="1">
  <creationDate>2015-12-22T03:28:01.4415782Z</creationDate>
  <activationDate>2015-12-22T03:28:01.4220469Z</activationDate>
  <expirationDate>2016-03-21T03:28:01.4220469Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNet.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
        <!-- Warning: the key below is in an unencrypted form. -->
        <value>f8XXfZXEBhPekaMUtccwv1cHkPV2j3TAtmgb2/WpDpvJgKGlWmZ7ZIQ+5wEx6nqOvKq+ppUMke8hbk1GGoxXXw==</value>
      </masterKey>
    </descriptor>
  </descriptor>
</key>
```

But the login does not work.

**Comment by blowdart** [comment]
You need to point the key directory to a *shared* directory which both applications can access. Putting it in c:\shared-auth-ticket-keys\ isn't enough in multiple server scenarios, as it's still going to create a key ring *local* to each machine. 

You need to create an UNC share somewhere that both applications can access, and use that, for example \\keystore\keystore

Or you implement a key store yourself suitable to your architecture, for example, using SQL Server.

**Comment by yuezhongxin** [comment]
@blowdart I tried, but there were following errors: 

```
2016-01-04 12:19:30.020 +08:00 [Error] An unhandled exception was thrown by the application.
System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '\\10.10.10.10\shared-auth-ticket-keys'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.DirectoryInfo.Create()
   at Microsoft.AspNet.DataProtection.Repositories.FileSystemXmlRepository.<GetAllElementsCore>d__15.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNet.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNet.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNet.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)
   at Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationHandler`1.<SignInAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CNBlogs.Ad.Web.Controllers.AccountController.<LoginSubmit>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingApplication.<ProcessRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__3.MoveNext()
```

**Comment by yuezhongxin** [comment]
I solved this problem, thank you very much!

**Comment by blowdart** [comment]
@yuezhongxin Could you share what the solution was, so I can update the docs to make it clearer? I assume it was a permissions problem at this point?

**Comment by yuezhongxin** [comment]
I am using this way you say:

>You need to create an UNC share somewhere that both applications can access, and use that, for example \keystore\keystore

Above that exception solution, you can see this [article](http://www.cnblogs.com/xishuai/p/aspnet-access-shared-folder.html).

**Comment by 717009629** [comment]
我用的rcl-final ，执行完HttpContext.Authentication.SignInAsync之后用户并没有被认证啊 ，求大神帮忙！！！

**Comment by 717009629** [comment]
![xl b p51pjy 6f3 d4swt m](https://cloud.githubusercontent.com/assets/16289643/12262316/21cf0304-b962-11e5-915e-d0a3852f33ad.png)

**Comment by yuezhongxin** [comment]
@717009629 身份验证在下个请求之后才会有效，你可以写个示例试试，比如身份验证后跳转到另外一个Aciton中。

**Comment by 717009629** [comment]
@yuezhongxin   我试了 singin之后跳转到 一个加了【authorize】的action之后 无限循环啊

**Comment by yuezhongxin** [comment]
@717009629 你程序打包发我邮箱下。xishuai@cnblogs.com

**Comment by 717009629** [comment]
@yuezhongxin 大神我发给你了

**Comment by yuezhongxin** [comment]
@717009629 我写了个示例，测试是可以的，已经邮箱发给你了。

**Comment by 717009629** [comment]
@yuezhongxin 谷歌我上不去啊

**Comment by yuezhongxin** [comment]
@717009629 http://pan.baidu.com/s/1Zd8i6

**Comment by 717009629** [comment]
@yuezhongxin  大神你给我例子在我机子上还是不行啊点击登陆 还是跳回 about界面

**Comment by 717009629** [comment]
@yuezhongxin  大神能加一下你的qq吗

**Comment by yuezhongxin** [comment]
@717009629 你再试试。

![untitled](https://cloud.githubusercontent.com/assets/6800671/12265538/89bd11e8-b978-11e5-8026-68f68ef7987d.gif)

**Comment by 717009629** [comment]
谢谢大神 果然是浏览的原因 @yuezhongxin

**Comment by 717009629** [comment]
@yuezhongxin 和代码没关系 郁闷死了 ，差点抓狂了

**Comment by yuezhongxin** [comment]
@717009629 😊
