### ISSUE TITLE
setting CallBackPath causes error 

### ISSUE THREAD

**Issue by kapoc** [aspnet/Security#693]
I have OpenId Connect set up & running together with Identity Server 4.  

Now, it works well but if I try to change options.CallBackPath to _any_ value, I get this, somewhat not very detailed error: 

```
Microsoft.AspNet.Hosting.Internal.HostingEngine: Error: Application startup exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: 
Parameter name: value
   at Microsoft.AspNet.Http.PathString..ctor(String value)
   at Microsoft.AspNet.Http.PathString.op_Implicit(String s)
   at Asw.Yefforts.API.Authentication.AuthenticationConfiguration.<>c.<ConfigureAuthentication>b__14_1(OpenIdConnectOptions options) in C:\repos<...>\Authentication\AuthenticationConfiguration.cs:line 113
   at Microsoft.AspNet.Builder.OpenIdConnectAppBuilderExtensions.UseOpenIdConnectAuthentication(IApplicationBuilder app, Action`1 configureOptions)
   at Asw.Yefforts.API.Authentication.AuthenticationConfiguration.ConfigureAuthentication(IApplicationBuilder app) in C:\repos<...>\Authentication\AuthenticationConfiguration.cs:line 97
   at Asw.Yefforts.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\repos<...>\Startup.cs:line 139
   --- End of inner exception stack trace ---
```

My connection options:

    app.UseCookieAuthentication(options =>
            {                
                options.AutomaticAuthenticate = true;
                
            });

    app.UseOpenIdConnectAuthentication(options =>
                {
                    options.AutomaticChallenge = true;
                    options.AuthenticationScheme = AuthenticationScheme;

                    options.Authority = IdServBaseUri;
                    options.ClientId = ClientId;
                    options.Scope.Add("openid");
                    options.Scope.Add("email");
                    options.Scope.Add("profile");
                    options.Scope.Add("roles");
                    options.Scope.Add("offline_access");
                    options.RequireHttpsMetadata = false;
                    options.PostLogoutRedirectUri = ClientUri;
                    options.ResponseType = ResponseType;
                    options.SaveTokensAsClaims = true;
                    options.CallbackPath = "http://loalhost:6004/auth/signin-oidc'
                 }

Does this mean just poorly described error (and wrong CallbackPath) or is this something else?

**Comment by Tratcher** [comment]
CallbackPath is just the path portion. Try `/auth/signin-oidc`
