### ISSUE TITLE
OAuth Middlware Issue with dnx541

### ISSUE THREAD

**Issue by aquiladev** [aspnet/Security#727]
Hi everyone,
We need to setup authorization for our APIs with own OAuth server.
We've tried to use custom middleware for own OAuth authorization, but we faced with some problems. After that we decided to simplify issue and check with middleware from Microsoft's Security package. We use GoogleAuthenticationMiddleware for it, but with we also faced with problems.

Startup.cs looks like:
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddAuthentication(options => options.SignInScheme = GoogleDefaults.AuthenticationScheme);

  services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  app.UseGoogleAuthentication(new GoogleOptions
  {
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    ClientId = "...",
    ClientSecret = "..."
  });

  ...

  app.UseMvc();
}
```

global.json
```
{
	"projects": [ "src", "tests" ],
	"sdk": {
		"version": "1.0.0-rc1-update1",
		"runtime": "clr",
		"architecture": "x64"
	}
}
```

project.json
```
{
	"version": "1.0.0-*",
	"compilationOptions": {
		"emitEntryPoint": true
	},
	"dependencies": {
		"Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
		"Microsoft.AspNet.Authentication.Google": "1.0.0-rc1-final",
		"Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-rc1-final",
		"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
		"Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
		"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
		"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
		"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
		"Serilog": "1.5.14",
		"Serilog.Extensions.Logging": "1.0.0-rc1-final-10092",
		"Serilog.Sinks.AzureTableStorage": "1.5.11",
		"Serilog.Sinks.Seq": "2.0.0-beta-30",
		"System.Linq.Parallel": "4.0.1-beta-23516",
		"WindowsAzure.Storage": "6.2.0"
	},
	"commands": {
		"web": "Microsoft.AspNet.Server.Kestrel --server.urls http://localdev.tkit.com:15645/"
	},
	"frameworks": {
		"dnx451": {
		}
	},
	"exclude": [
		"wwwroot",
		"node_modules"
	],
	"publishExclude": [
		"**.user",
		"**.vspscc"
	]
}
```

Authorization process throws exception like this:
```
dnx.exe Error: 0 : 2016-03-04 11:17:09.068 +02:00 [Error] An unhandled exception was thrown by the application.
System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.HandleSignInAsync(SignInContext context)
   at Microsoft.AspNet.Authentication.AuthenticationHandler`1.<SignInAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```

It happens during request from OAuth server to our API with url like this:
```
http://localdev.tkit.com:15645/signin-google?state=...&code=...&authuser=0&session_state=...&prompt=none#
```

**Comment by Tratcher** [comment]
You need cookies:
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddAuthentication(options => options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

  services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  app.UseCookieAuthentication(new CookieAuthenticationOptions
  {
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
  });

  app.UseGoogleAuthentication(new GoogleOptions
  {
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    ClientId = "...",
    ClientSecret = "..."
  });

  ...

  app.UseMvc();
}
```
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs
