### ISSUE TITLE
[Question] Why would I get "Unable to resolve service for type 'xxxOptions' "?

### ISSUE THREAD

**Issue by redknightlois** [aspnet/Security#781]
Hi guys,

Been trying to figure out this for a long time already, with no luck and/or idea why it happens. I am using RC1-Update2 on the CLR. 

I am building the scafolding to put an API Key authentication token in there. The code looks like this: https://gist.github.com/redknightlois/0178c0abf9d7c6e5584f1e0ccab901df

I have both: ```services.AddAuthentication(sharedOptions => sharedOptions.SignInScheme = "Token");``` and ```app.UseTokenAuthentication();``` in the startup code. But I get the following error:

```
Test Name:	AuthenticationOperationTests.LoginAndLogoff
Test FullName:	AuthenticationOperationTests.LoginAndLogoff
Test Source:	AuthenticationOperation.cs : line 105
Test Outcome:	Failed
Test Duration:	0:00:03,759

Result StackTrace:	
at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNet.Builder.UseMiddlewareExtensions.<>c__DisplayClass2_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNet.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.TestHost.TestServer..ctor(WebHostBuilder builder)

Result Message:	Unable to resolve service for type 'TokenAuthenticationOptions' while attempting to activate 'TokenAuthenticationMiddleware'.
```

The part that doesnt make sense to me is that ```TokenAuthenticationOptions``` shouldnt require any registered service. Any idea why this may be happening?

**Comment by Tratcher** [comment]
You either need to register it or change your constructor to take `IOptions<TokenAuthenticationOptions>`.

**Comment by redknightlois** [comment]
Awesome!!! Worked like a charm!!! Thanks.
