### ISSUE TITLE
403 error when using google authentication

### ISSUE THREAD

**Issue by Strandedpirate** [aspnet/Security#818]
Getting a 403 forbidden error while using the google authentication when the _EnsureSuccessStatusCode_ method is called. I get to the "allow" screen on google's side, I grant my app access to my account but then it bombs out after redirecting back to my app. I tried setting the TokenEndpoint to "https://accounts.google.com/o/oauth2/token" instead of the hard-coded default but it didn't help; same error. 

What else can I try to resolve this?

The facebook authentication has the same status code check and it is working just fine.

**My setup:**
```
app.UseGoogleAuthentication(new Microsoft.AspNet.Authentication.Google.GoogleOptions
{
	SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme,
	ClientId = Configuration["OAuth:google:clientid"],
	ClientSecret = Configuration["OAuth:google:clientsecret"],
	CallbackPath = new PathString(Configuration["OAuth:google:callbackpath"]),
	AutomaticAuthenticate = true,
	AutomaticChallenge = true,
});
```

**Error:**
```
An unhandled exception has occurred: Response status code does not indicate success: 403 (Forbidden).
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNet.Authentication.Google.GoogleHandler.<CreateTicketAsync>d__1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.OAuth.OAuthHandler`1.<HandleRemoteAuthenticateAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__0.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by Tratcher** [comment]
This is probobly a duplicate of https://github.com/aspnet/Security/issues/53

**Comment by Strandedpirate** [comment]
Thanks, for me it was a simple matter of enabling Google+ API.

https://console.developers.google.com/apis
Google+ API > Enable
