### ISSUE TITLE
Error: Configuration value 'Verbose' for category 'Default' is not supported in AuthenticationMiddleware ctr

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/Security#840]
this is for rc2 version of code.

If there is this line in `Startup.Configure`

`loggerFactory.AddConsole(Configuration.GetSection("Logging"));` // It's exist there by default btw

than Implementation of `AuthenticationMiddleware` throws `InvalidOperationException` when call base class constructor. `"Configuration value 'Verbose' for category 'Default' is not supported."`

Stacktrace:
```
at Microsoft.Extensions.Logging.Console.ConfigurationConsoleLoggerSettings.TryGetSwitch(String name, LogLevel& level)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.GetFilter(String name, IConsoleLoggerSettings settings)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.Logger..ctor(LoggerFactory loggerFactory, String name)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1..ctor(RequestDelegate next, IOptions`1 options, ILoggerFactory loggerFactory, UrlEncoder encoder)
   at Test.AuthMiddleware..ctor(RequestDelegate next, IOptions`1 options, ILoggerFactory loggerFactory, UrlEncoder encoder)
```

**Comment by Tratcher** [comment]
Please move this to the Logging repo, it looks like an issue with the Console logger.

**Comment by ivankarpey** [comment]
Moved to https://github.com/aspnet/Logging/issues/436 
Closing there.
