### ISSUE TITLE
JwtBearerMiddleware instantiation issues in integration tests.

### ISSUE THREAD

**Issue by hsorbo** [aspnet/Security#875]
Souldn't  app.UseJwtBearerAuthentication work without explicitly adding UrlEncoder to DI when Integration-testing?

```
System.InvalidOperationException : Unable to resolve service for type 'System.Text.Encodings.Web.UrlEncoder' while attempting to activate 'Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware'.
      Stack Trace:
           at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
           at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
           at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
           at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
           at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
           at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
           at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
           at ConsoleApplication.TestTest.<Blupp>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Example test.

```csharp
namespace X
{
    public class Startup
    {
         public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
         {
            app.UseJwtBearerAuthentication(new JwtBearerOptions());
         }
    }

    public class TestTest
    {
        [Fact]
        public async Task Test()
        {
            var builder  = new WebHostBuilder().UseStartup<Startup>();
            var server = new TestServer(builder);
        }
    }
}
```

adding this to Startup resolves the issue

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddScoped<System.Text.Encodings.Web.UrlEncoder>(_ => System.Text.Encodings.Web.UrlEncoder.Default);
}
```

**Comment by Tratcher** [comment]
UrlEncoder is required by the base class AuthenticationMiddleware. `services.AddAuthentication()` will register it for you.

**Comment by hsorbo** [comment]
Thanks

**Comment by pchamakura** [comment]
Thank you. This saved the day for me!
