### ISSUE TITLE
Web Api using integrated windows authentication

### ISSUE THREAD

**Issue by vinny-Jo** [aspnet/Security#923]
My visual studio solution contains 2 projects ( web site, web api). both are set to use windows authentication.
When calling my Web Api on Client Side with the following code Ajax call 
```  
contentType: "application/json; charset=utf-8",
                        url: "http://localhost:5001/api/financialtargets/GetAllFinancialTargets",
                        type: "GET",
                        dataType: "json",
                        xhrFields: {
                            withCredentials: true
                        },

                        beforeSend: function (req) {
                            req.setRequestHeader('Access-Control-Allow-Origin', '*');
                            req.setRequestHeader('Access-Control-Allow-Methods', 'GET,POST,PATCH,PUT,DELETE,OPTIONS');
                        }
```

**I am getting the following exception:**
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKTM48QA0B54": An unhandled exception was thrown by the application.
System.InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic  at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<ChallengeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeResultAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke>d__3.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.RequestProcessingAsync>d__2.MoveNext()
```
**My Web Api project.json:**
```
"dependencies": {
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Authorization": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Cors": "1.0.0",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.FileProviders.Physical": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Newtonsoft.Json": "9.0.1",
    "PHMG.ProspX.BusinessLogic": "1.0.0-*",
    "PHMG.ProspX.Data": "1.0.0-*",
    "PHMG.ProspX.Security": "1.0.0-*"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --server.urls=http://localhost:5001"
  },
```

**web api startup.cs:**
```
public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
           
            services.AddBusinessLogic();
            services.AddData();
            services.AddCors(options => options.AddPolicy("AllowAll", p => p.AllowAnyOrigin()
                                                                    .AllowAnyMethod()
                                                                     .AllowAnyHeader()
                                                                     .AllowCredentials()));
            // Add MVC services to the services container.
            services.AddMvc(
            // Only allow authenticated users.
            setup =>
            {
                setup.Filters.Add(
                    new AuthorizeFilter(
                        new AuthorizationPolicyBuilder()
                            .RequireAuthenticatedUser()
                            .Build()));

            }).AddJsonOptions(a => a.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            app.UseStaticFiles();

            // Add MVC to the request pipeline.
            app.UseCors("AllowAll");

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "api/{controller}/{action}"
                    );
            });

        }
    }
```

**and web Api program.cs**

```
public static void Main(string[] args)
        {
                var host = new WebHostBuilder()
                .UseUrls("http://localhost:5001")
                .UseKestrel()
                .UseIISIntegration()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();
            host.Run();
        }
```

**Comment by Tratcher** [comment]
It looks like you're running Kestrel directly, correct? Kestrel does not support windows auth, you need to use IIS/Express.

**Comment by vinny-Jo** [comment]
Hi Chris,

yes, I am using kestrel because iisexpress does not worked with [cors]. I am using postman to check the headers passed to the web service, with kestrel: the web service accept and recognized windows auth token (cookie) and 'Access-Control-Allow-Origin', where as iisexperss does not recognized the headers Access-Control-Allow-Origin and the windows Auth token and reject the call.  

Is there a way to use middleware authentication with ntlm or cookie handler with kestrel (sample).
or if iisexpress, how can I resolve my cors issue...

**Comment by Tratcher** [comment]
There is no middleware available for NTLM. Focus on your CORS issue. This looks related: https://github.com/aspnet/CORS/issues/81

**Comment by vinny-Jo** [comment]
sorry but the CORS issue is not related at all, look at my code 
 services.AddCors(options => options.AddPolicy("AllowAll", p => p.AllowAnyOrigin()
       .AllowAnyMethod().AllowAnyHeader().AllowCredentials()));

iisexperss cors handler does not recognized the headers Access-Control-Allow-Origin, the windows Auth token and reject the call. It is not an opaque call or domain issue. 

if the Web service and web site are in the same project using Kestrel.
My programs main has got the weblistner configured has followed:
 .UseWebListener(
                    webOpts => { webOpts.Listener.AuthenticationManager.AuthenticationSchemes = AuthenticationSchemes.NTLM; }
                )
NTLM works fine the token is passed through the back end. My web site is configured with kestrel / webpack / Aurelia. So is there an option to use NTLM listener in the web service  instead of a middleware?

**Comment by Eilon** [comment]
We'll take another look at this, thanks for the extra info.

**Comment by Eilon** [comment]
@kichalla can you take a look and see if maybe there's an issue in CORS?

**Comment by kichalla** [comment]
@vinny-Jo : You seem to be adding `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods` headers to the request. They are response headers sent by the server.

You should **not** be needing to add the following request headers yourself as the browser does it automatically.
The HTTP request headers:
- Origin
- Access-Control-Request-Method
- Access-Control-Request-Headers

**Comment by kichalla** [comment]
Closing this issue now. You can take a look at my above comment and try again. If you still see an issue, feel free to re-open this issue with more details.
