### ISSUE TITLE
AD FS OAuth2: NotSupportedException: Specified method is not supported

### ISSUE THREAD

**Issue by jworley** [aspnet/Security#948]
I am attempting to follow the tutorial found here: https://vcsjones.com/2015/05/04/authenticating-asp-net-5-to-ad-fs-oauth/ to configure OAuth authentication with an AD FS server.

This is my raw exception:

```
System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleSignInAsync(SignInContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

This is my `ConfigureServices()` method: 
```
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();

            services.AddAuthentication(opts => opts.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

            services.Configure<OAuthOptions>(opt =>
            {
                opt.AutomaticAuthenticate = true;
                opt.AutomaticChallenge = true;
                opt.AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                opt.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                opt.ClientId = "44ADBF90-0626-4730-8EC7-2D007F59B8D3";
                opt.ClientSecret = "abc123!";
                opt.CallbackPath = new PathString("/oauth-callback");
                opt.Events = new OAuthEvents
                {
                    OnRedirectToAuthorizationEndpoint = ctx =>
                    {
                        var parameter = new Dictionary<string, string>
                        {
                            ["resource"] = "https://myapp.dev"
                        };
                        var query = QueryHelpers.AddQueryString(ctx.RedirectUri, parameter);
                        ctx.Response.Redirect(query);
                        return Task.FromResult(0);
                    },
                    OnCreatingTicket = ctx =>
                    {
                        var token = new JwtSecurityToken(ctx.AccessToken);
                        var identity = new ClaimsIdentity(token.Claims, ctx.Options.AuthenticationScheme, "upn", "role");
                        ctx.Ticket = new AuthenticationTicket(new ClaimsPrincipal(identity), ctx.Ticket.Properties, ctx.Options.AuthenticationScheme);
                        return Task.FromResult(0);
                    }
                };
                opt.ClaimsIssuer = "https://myapp.dev";
                opt.AuthorizationEndpoint = "https://adfs.mycompany.com/adfs/oauth2/authorize/";
                opt.TokenEndpoint = "https://adfs.mycompany.com/adfs/oauth2/token/";
            });

            services.Configure<CookieAuthenticationOptions>(opt =>
            {
                opt.AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                opt.AutomaticAuthenticate = true;
                opt.AutomaticChallenge = true;
            });
        }
```

And my `Configure()` method:
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseCookieAuthentication();
            app.UseOAuthAuthentication();

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

```

Thank you in advance for any advice you can provide.

**Comment by Tratcher** [comment]
```
services.Configure<OAuthOptions>(opt =>
            {
                opt.AutomaticAuthenticate = true;
                opt.AutomaticChallenge = true;
                opt.AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                opt.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
```

Your AuthenticationScheme is wrong, it should be a unique identifier for the OAuth instance like "MyOAuth"

**Comment by jworley** [comment]
Thank you, that worked.
